name: Build and deploy

env:
  NODE_VERSION: '12'

on:
  push:
     branches: [ main ]

jobs:
  build-and-deploy:
     name: Build and deploy
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Get branch name
        shell: bash
        run: echo BRANCH_NAME=${GITHUB_REF#refs/heads/} >> $GITHUB_ENV

      - name: Cache packages
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ hashFiles('package-lock.json') }}

      - name: Install packages
        run: npm ci

      - name: Build app
        run: |
          npm run build
#         gatsby puts static files in 'public' directory
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SERVER_SSH_KEY }}
          known_hosts: "malyshev.pro,195.2.92.114 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBAxqO1p6Uv6BBKPkdqDFWcc+qLgHIrIkdvxBdcKufTaxJiUQ/KTas3OLZFpiVa006URirqta0WrCFe70xd1VTcY="

      - name: Send to SSH
        run: |
          scp -r public/* ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/root/blog
